-- Create Schemas
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'UserAuth')
    EXEC('CREATE SCHEMA UserAuth');
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'UserRole')
    EXEC('CREATE SCHEMA UserRole');
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'Entity')
    EXEC('CREATE SCHEMA Entity');
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'Company')
    EXEC('CREATE SCHEMA Company');
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'Org')
    EXEC('CREATE SCHEMA Org');

-- Role Table
CREATE TABLE UserRole.[Role] (
    RoleId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    RoleKey INT IDENTITY(1,1) NOT NULL,
    RoleName NVARCHAR(50) NOT NULL UNIQUE,
    Description NVARCHAR(255),
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Role PRIMARY KEY NONCLUSTERED (RoleId),
    CONSTRAINT UX_Role_RoleKey UNIQUE CLUSTERED (RoleKey)
);

-- Permission Table
CREATE TABLE UserRole.Permission (
    PermissionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    PermissionKey INT IDENTITY(1,1) NOT NULL,
    PermissionName NVARCHAR(100) NOT NULL UNIQUE,
    Description NVARCHAR(255),
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Permission PRIMARY KEY NONCLUSTERED (PermissionId),
    CONSTRAINT UX_Permission_PermissionKey UNIQUE CLUSTERED (PermissionKey)
);

-- RolePermission Junction Table
CREATE TABLE UserRole.RolePermission (
    RolePermissionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    RolePermissionKey INT IDENTITY(1,1) NOT NULL,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    PermissionId UNIQUEIDENTIFIER NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_RolePermission PRIMARY KEY NONCLUSTERED (RolePermissionId),
    CONSTRAINT UX_RolePermission_RolePermissionKey UNIQUE CLUSTERED (RolePermissionKey),
    CONSTRAINT FK_RolePermission_Role FOREIGN KEY (RoleId) REFERENCES UserRole.Role(RoleId),
    CONSTRAINT FK_RolePermission_Permission FOREIGN KEY (PermissionId) REFERENCES UserRole.Permission(PermissionId)
);

-- UserAccount Table
CREATE TABLE UserAuth.UserAccount (
    UserAccountId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    UserAccountKey INT IDENTITY(1,1) NOT NULL,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    PasswordSalt NVARCHAR(255) NOT NULL,
    HashAlgorithmId INT NOT NULL, -- Optional FK if you create a HashAlgorithm table
    EmailConfirmed BIT NOT NULL DEFAULT 0,
    ConfirmationToken NVARCHAR(255) NULL,
    TokenGeneratedAt DATETIME NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    LastLoginAt DATETIME NULL,
    CONSTRAINT PK_UserAccount PRIMARY KEY NONCLUSTERED (UserAccountId),
    CONSTRAINT UX_UserAccount_UserAccountKey UNIQUE CLUSTERED (UserAccountKey)
);

-- UserProfile Table
CREATE TABLE UserAuth.UserProfile (
    UserProfileId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    UserProfileKey INT IDENTITY(1,1) NOT NULL,
    UserAccountId UNIQUEIDENTIFIER NOT NULL,
    UserType NVARCHAR(50) NOT NULL, -- 'Orphan', 'Manager', 'Person'
    EntityId UNIQUEIDENTIFIER NOT NULL, -- GUID FK referencing specific entity
    RoleId UNIQUEIDENTIFIER NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_UserProfile PRIMARY KEY NONCLUSTERED (UserProfileId),
    CONSTRAINT UX_UserProfile_UserProfileKey UNIQUE CLUSTERED (UserProfileKey),
    CONSTRAINT FK_UserProfile_UserAccount FOREIGN KEY (UserAccountId) REFERENCES UserAuth.UserAccount(UserAccountId),
    CONSTRAINT FK_UserProfile_Role FOREIGN KEY (RoleId) REFERENCES UserRole.Role(RoleId)
);

-- Orphan Table
CREATE TABLE Entity.Orphan (
    OrphanId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    OrphanKey INT IDENTITY(1,1) NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Gender NVARCHAR(10),
    AdmissionDate DATE,
    CurrentStatus NVARCHAR(50),
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Orphan PRIMARY KEY NONCLUSTERED (OrphanId),
    CONSTRAINT UX_Orphan_OrphanKey UNIQUE CLUSTERED (OrphanKey)
);

-- Manager Table
CREATE TABLE Entity.Manager (
    ManagerId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ManagerKey INT IDENTITY(1,1) NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    CompanyId UNIQUEIDENTIFIER NOT NULL,
    Designation NVARCHAR(100),
    PhoneNumber NVARCHAR(20),
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Manager PRIMARY KEY NONCLUSTERED (ManagerId),
    CONSTRAINT UX_Manager_ManagerKey UNIQUE CLUSTERED (ManagerKey),
    CONSTRAINT FK_Manager_Company FOREIGN KEY (CompanyId) REFERENCES Company.[Company](CompanyId)
);

-- Person Table
CREATE TABLE Entity.Person (
    PersonId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    PersonKey INT IDENTITY(1,1) NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    PhoneNumber NVARCHAR(20),
    DateOfBirth DATE,
    Address NVARCHAR(500),
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Person PRIMARY KEY NONCLUSTERED (PersonId),
    CONSTRAINT UX_Person_PersonKey UNIQUE CLUSTERED (PersonKey)
);

-- Company Table
CREATE TABLE Company.Company (
    CompanyId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    CompanyKey INT IDENTITY(1,1) NOT NULL,
    CompanyName NVARCHAR(200) NOT NULL UNIQUE,
    Industry NVARCHAR(100),
    ContactEmail NVARCHAR(255),
    Address NVARCHAR(500),
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Company PRIMARY KEY NONCLUSTERED (CompanyId),
    CONSTRAINT UX_Company_CompanyKey UNIQUE CLUSTERED (CompanyKey)
);

-- Org Table (Organization / Orphanage)
CREATE TABLE Org.Org (
    OrgId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    OrgKey INT IDENTITY(1,1) NOT NULL,
    OrgName NVARCHAR(200) NOT NULL UNIQUE,
    Address NVARCHAR(500),
    ContactEmail NVARCHAR(255),
    PhoneNumber NVARCHAR(20),
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Org PRIMARY KEY NONCLUSTERED (OrgId),
    CONSTRAINT UX_Org_OrgKey UNIQUE CLUSTERED (OrgKey)
);

-- OrphanOrg Junction Table
CREATE TABLE Org.OrphanOrg (
    OrphanOrgId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    OrphanOrgKey INT IDENTITY(1,1) NOT NULL,
    OrphanId UNIQUEIDENTIFIER NOT NULL,
    OrgId UNIQUEIDENTIFIER NOT NULL,
    AssociationStartDate DATE NOT NULL,
    AssociationEndDate DATE NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_OrphanOrg PRIMARY KEY NONCLUSTERED (OrphanOrgId),
    CONSTRAINT UX_OrphanOrg_OrphanOrgKey UNIQUE CLUSTERED (OrphanOrgKey),
    CONSTRAINT FK_OrphanOrg_Orphan FOREIGN KEY (OrphanId) REFERENCES Entity.Orphan(OrphanId),
    CONSTRAINT FK_OrphanOrg_Org FOREIGN KEY (OrgId) REFERENCES Org.Org(OrgId)
);

-- ManagerOrg Junction Table
CREATE TABLE Org.ManagerOrg (
    ManagerOrgId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ManagerOrgKey INT IDENTITY(1,1) NOT NULL,
    ManagerId UNIQUEIDENTIFIER NOT NULL,
    OrgId UNIQUEIDENTIFIER NOT NULL,
    AssociationStartDate DATE NOT NULL,
    AssociationEndDate DATE NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    fcb UNIQUEIDENTIFIER NOT NULL,
    lub UNIQUEIDENTIFIER NOT NULL,
    fcd DATETIME NOT NULL DEFAULT GETDATE(),
    lud DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_ManagerOrg PRIMARY KEY NONCLUSTERED (ManagerOrgId),
    CONSTRAINT UX_ManagerOrg_ManagerOrgKey UNIQUE CLUSTERED (ManagerOrgKey),
    CONSTRAINT FK_ManagerOrg_Manager FOREIGN KEY (ManagerId) REFERENCES Entity.Manager(ManagerId),
    CONSTRAINT FK_ManagerOrg_Org FOREIGN KEY (OrgId) REFERENCES Org.Org(OrgId)
);
